apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: minio-bucket-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-bucket
        image: minio/mc:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            mc alias set minio http://minio-service.{{.Release.Namespace}}.svc.cluster.local:9000 \
              "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}" --api S3v4;

            mc mb --ignore-existing minio/${MINIO_DEFAULT_BUCKET};
            if [ $$? -ne 0 ]; then
              exit 1
            fi
        env:
        - name: MC_CONFIG_DIR
          value: "/tmp"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_USER
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_PASSWORD
        - name: MINIO_DEFAULT_BUCKET
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: DEFAULT_BUCKET
  backoffLimit: 3